FROM node:latest
WORKDIR /app
COPY ["ci/wait-for-it.sh", "./"]
COPY ["package.json", "package-lock.json*", "./"]
RUN chmod +x wait-for-it.sh
RUN npm install
COPY . .
CMD ./wait-for-it.sh mongodb:27017 -t 60 -- npm run test:integration
